version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped